name: CI CD con Release
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-test-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: Configurar JDK 25
        uses: actions/setup-java@v6.0.1
        with:
            distribution: 'temurin'
            java-version: '25'
      - name: Compilar el proyecto
        run: mvn clean package -DskipTests
      - name: Arrancar Modulo A
        run: |
            nohup java -jar moduloa/target/moduloa-0.0.1-SNAPSHOT.jar \
            > moduloa.log 2>&1 &

      - name: Esperar Modulo A
        run: |
                for i in {1..30}; do
                  if curl -fs http://localhost:8081/saludo; then
                    echo "Modulo A está disponible"
                    break
                  fi
                
                  echo "Esperando Modulo A..."
                  sleep 2
                done
                
                curl -fs http://localhost:8081/saludo

      - name: Arrancar Modulo B
        run: |
                nohup java -jar modulob/target/modulob-0.0.1-SNAPSHOT.jar \
                  > modulob.log 2>&1 &

      - name: Esperar Modulo B
        run: |
                for i in {1..30}; do
                  if curl -fs http://localhost:8082/consume-a; then
                    echo "Modulo B está disponible"
                    break
                  fi
                
                  echo "Esperando Modulo B..."
                  sleep 2
                done
                
                curl -fs http://localhost:8082/consume-a

      - name: Ejecutar tests
        run: mvn test

      - name: Crear release y subir assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: |
            moduloa/target/moduloa-0.0.1-SNAPSHOT.jar
            modulob/target/modulob-0.0.1-SNAPSHOT.jar
            moduloc/target/moduloc-0.0.1-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Creando el release en Github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v3.0.0
          release_name: "Release v3.0.0"
          draft: 'false'
          prerelease: 'false'
      - name: Upload de un asset en el release (usando upload-release-asset)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./moduloa/target/moduloa-0.0.1-SNAPSHOT.jar
          asset_name: ModuloA.jar
          asset_content_type: application/java-archive

  generar-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: Configurar JDK 25
        uses: actions/setup-java@v6.0.1
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Compilando todos los módulos
        run: mvn clean package -DskipTests
      - name: Listar todos los ejecutables *.jar
        run: find . -type f -name "*.jar"
      - name: Upload de todos los JARs
        uses: actions/upload-artifact@v7.0.1
        with:
          name: springboot-modulos
          path: |
            moduloc/target/*.jar
            modulob/target/*.jar
            moduloa/target/*.jar
      - name: Upload de un JAR (ejemplo)
        uses: actions/upload-artifact@v7.0.1
        with:
          name: modulo_a
          path: moduloa/target/*.jar
      - name: Download de todos los JARs
        uses: actions/download-artifact@v8.0.1
        with:
          name: springboot-modulos
          path: ./ejecutables
      - name: Mostrando JARs descargados
        run: ls -R ./ejecutables
      - name: Download de un JAR (ejemplo)
        uses: actions/download-artifact@v8.0.1
        with:
          name: modulo_a
          path: ./ejecutable_modulo_a
      - name: Mostrando JARs descargados
        run: ls -R ./ejecutable_modulo_a
